---
- name: Update AWS Server
  hosts: web1
  become: yes
  
  tasks:
  - name: install git
    yum:
     name: git
     state: present
    when: ansible_distrubition == Centos or ansible_distribution == Amazon

  - name :deploy
    git
     repo: https://github.com/ravi2krishna/ecomm.git
     dest: /var/www/html
    when: ansible_distrubition == Centos or ansible_distribution == Amazon

...
