---
- name: Update AWS Server
  hosts: all

  become: yes

  tasks:
  - name: Install httpd 
    yum:
     name: httpd
     state: present
    when: ansible_distribution == "CentOS" or  ansible_distribution == "Amazon"

  - name: Start httpd
    service:
     name: httpd
     state: started
    when: ansible_distribution == "CentOS" or  ansible_distribution == "Amazon"


  - name: Enable httpd
    service:
     name: httpd
     enabled: yes
    when: ansible_distribution == "CentOS" or  ansible_distribution == "Amazon"


  
        




...
